# -*- coding: utf-8 -*-
"""app-deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1Oy_7BtB26JefttaUU-V4-GgxVMeil1
"""

import sys
!{sys.executable} -m pip install streamlit
import streamlit as st

st.set_page_config(page_title="Calculator App", page_icon="🧮")

st.title("🧮 Calculator App")
st.write("Simple Calculator deployed on Streamlit")

# Inputs
num1 = st.number_input("Enter first number", value=0.0)
num2 = st.number_input("Enter second number", value=0.0)

operation = st.radio(
    "Select Operation",
    ("Addition", "Subtraction", "Multiplication", "Division")
)

if st.button("Calculate"):
    if operation == "Addition":
        st.success(f"Result: {num1 + num2}")

    elif operation == "Subtraction":
        st.success(f"Result: {num1 - num2}")

    elif operation == "Multiplication":
        st.success(f"Result: {num1 * num2}")

    elif operation == "Division":
        if num2 == 0:
            st.error("❌ Division by zero not allowed")
        else:
            st.success(f"Result: {num1 / num2}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile calculator_app.py
# 
# import streamlit as st
# 
# st.set_page_config(page_title="Calculator App", page_icon="🧮")
# 
# st.title("🧮 Calculator App")
# st.write("Simple Calculator deployed on Streamlit")
# 
# # Inputs
# num1 = st.number_input("Enter first number", value=0.0)
# num2 = st.number_input("Enter second number", value=0.0)
# 
# operation = st.radio(
#     "Select Operation",
#     ("Addition", "Subtraction", "Multiplication", "Division")
# )
# 
# if st.button("Calculate"):
#     if operation == "Addition":
#         st.success(f"Result: {num1 + num2}")
# 
#     elif operation == "Subtraction":
#         st.success(f"Result: {num1 - num2}")
# 
#     elif operation == "Multiplication":
#         st.success(f"Result: {num1 * num2}")
# 
#     elif operation == "Division":
#         if num2 == 0:
#             st.error("❌ Division by zero not allowed")
#         else:
#             st.success(f"Result: {num1 / num2}")

"""Now that the Streamlit code is saved to `calculator_app.py`, you can run it. However, to access the Streamlit UI from your browser, you'll need to set up a tunneling service, such as `ngrok`. This will create a publicly accessible URL for your Streamlit app running in Colab."""

# Kill any previously running Streamlit process (if any)
!kill $(lsof -t -i:8501)

# Install localtunnel
!npm install -g localtunnel

# Run the Streamlit app in the background
!streamlit run calculator_app.py &>/dev/null&

# Expose port 8501 using localtunnel
# This command will print the public URL. Copy and paste it into your browser.
!lt --port 8501

# Install ngrok if you haven't already
!pip install pyngrok

# Authenticate ngrok (replace 'YOUR_NGROK_AUTH_TOKEN' with your actual token)
# You can get a free auth token from ngrok.com after signing up.
from pyngrok import ngrok

# Replace with your ngrok auth token if you have one
# ngrok.set_auth_token("YOUR_NGROK_AUTH_TOKEN")

# Start ngrok tunnel
# Streamlit typically runs on port 8501
public_url = ngrok.connect(8501)
print(f"Streamlit App URL: {public_url}")

# Run the Streamlit app in the background
!streamlit run calculator_app.py &>/dev/null&

