# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTEkdXiIVFGXNZoT2Jj9GUBG-MAJquVX
"""

!pip install streamlit pyngrok

from pyngrok import ngrok

# IMPORTANT: Replace "PASTE_YOUR_NGROK_TOKEN_HERE" with your actual ngrok authtoken.
# You can find your authtoken on the ngrok dashboard: https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token("396W2rIUavPEIPlA2ZMcNSRQyO0_2ZYb16sauNdgidk2tghxx")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.set_page_config(page_title="Streamlit on Colab")
# 
# st.title(" Streamlit App Running on Google Colab")
# st.write("Hello! This app is running using ngrok.")
# st.slider("Pick a number", 0, 100, 50)
#

!streamlit run app.py &>/content/logs.txt &

public_url = ngrok.connect(8501)
print("Streamlit App URL:", public_url)

from pyngrok import ngrok

# Terminate all ngrok tunnels started by pyngrok in this session
ngrok.kill()

print("All ngrok tunnels started by pyngrok in this session have been killed.")

"""If you are still experiencing issues with too many tunnels, or if you had tunnels running from previous sessions, you can manage and close all your active tunnels directly from the [ngrok dashboard](https://dashboard.ngrok.com/tunnels/endpoints)."""

