# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1Oy_7BtB26JefttaUU-V4-GgxVMeil1
"""

import ipywidgets as widgets
from IPython.display import display

num1 = widgets.FloatText(description="Number 1")
num2 = widgets.FloatText(description="Number 2")

result = widgets.Label(value="Result:")

def add(b):
    result.value = f"Result: {num1.value + num2.value}"

def sub(b):
    result.value = f"Result: {num1.value - num2.value}"

def mul(b):
    result.value = f"Result: {num1.value * num2.value}"

def div(b):
    if num2.value == 0:
        result.value = "❌ Division by zero"
    else:
        result.value = f"Result: {num1.value / num2.value}"

add_btn = widgets.Button(description="Add")
sub_btn = widgets.Button(description="Subtract")
mul_btn = widgets.Button(description="Multiply")
div_btn = widgets.Button(description="Divide")

add_btn.on_click(add)
sub_btn.on_click(sub)
mul_btn.on_click(mul)
div_btn.on_click(div)

display(num1, num2, add_btn, sub_btn, mul_btn, div_btn, result)

